<?php
/**
 * Cardpay Solutions, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * PHP version 5
 * 
 * @category  Cardpay
 * @package   Cardpay_PayeezyLevel3
 * @copyright Copyright (c) 2015 Cardpay Solutions, Inc. (http://www.cardpaysolutions.com)
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<?php
    $id = Mage::app()->getRequest()->getParam('id');
    $card = Mage::getModel('payeezylevel3/creditcard')->load($id);
?>
<div class="page-title">
    <h1><?php echo $this->__('Delete Credit Card') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getDeleteConfirmUrl($card->getId()) ?>" method="post" id="delete-form">
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Please confirm that you want to delete this credit card') ?></h2>
        <ul class="form-list">
            <li>
                <b><?php echo $this->__('Credit Card Type'); ?></b>
            </li>
            <li>
                <?php echo $card->getCardTypeName(); ?>
            </li>
            <li>
                <b><?php echo $this->__('Credit Card Number'); ?></b>
            </li>
            <li>
                <?php echo $card->getMaskedCardNum(); ?>
            </li>
            <li>
                <b><?php echo $this->__('Expiration Date'); ?></b>
            </li>
            <li>
                <?php echo $card->getCcExpMonth() . '/' . $card->getCcExpYear(); ?>
            </li>
            <li>
                <b><?php echo $this->__('Cardholder Name'); ?></b>
            </li>
            <li>
                <?php echo $card->getCardholderName(); ?>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <button type="submit" class="button" title="<?php echo $this->__('Delete') ?>"><span><span><?php echo $this->__('Delete') ?></span></span></button>
        <p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    </div>    
</form>