<?php
/**
 * Cardpay Solutions, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * PHP version 5
 * 
 * @category  Cardpay
 * @package   Cardpay_PayeezyLevel3
 * @copyright Copyright (c) 2015 Cardpay Solutions, Inc. (http://www.cardpaysolutions.com)
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<?php
$_code = $this->getMethodCode();
$_model = Mage::getModel('payeezylevel3/creditcard');
$_savedCards = $_model->adminCustomerCards();
$_useVault = $_model->useVault() && count($_savedCards);
?>
<ul id="payment_form_<?php echo $_code ?>" style="display:none">
    <?php if ($_useVault): ?>
    <li id="<?php echo $_code ?>_token_selector">
        <label for="<?php echo $_code ?>_cc_token"><?php echo $this->__('Payment Information') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_token" name="payment[token]">
                <?php $_token = $this->getInfoData('token') ?>
                    <option value="">Select Saved Card</option>
                <?php foreach ($_savedCards as $card): ?>
                    <option value="<?php echo $card->getId() ?>" <?php if($card->getId() == $_token): ?>selected="selected"<?php endif ?>>
                        <?php echo $card->getMaskedCardNum() . ' - ' . $card->getCardTypeName(); ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </li>
    <li class="hide-if-token"><p>-- OR --</p></li>
    <?php endif; ?>
    <li class="hide-if-token">
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_type"><?php echo Mage::helper('payment')->__('Credit Card Type') ?> <span class="required">*</span></label><br/>
            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
            <?php $_ccType = $this->getInfoData('cc_type') ?>
                <option value=""></option>
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                <option value="<?php echo $_typeCode ?>" <?php if($_typeCode==$_ccType): ?>selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <li class="hide-if-token">
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_number"><?php echo Mage::helper('payment')->__('Credit Card Number') ?> <span class="required">*</span></label><br/>
            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo Mage::helper('payment')->__('Credit Card Number') ?>" class="input-text validate-cc-number" value="<?php echo $this->getInfoData('cc_number')?>"/>
        </div>
    </li>
    <li class="hide-if-token">
        <div class="input-box">
            <label for="<?php echo $_code ?>_expiration"><?php echo Mage::helper('payment')->__('Expiration Date') ?> <span class="required">*</span></label><br/>
            <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="validate-cc-exp required-entry">
            <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
            <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                <option value="<?php echo $k ?>" <?php if($k==$_ccExpMonth): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
            <?php endforeach ?>
            </select>
            <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
            <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="required-entry">
            <?php foreach ($this->getCcYears() as $k=>$v): ?>
                <option value="<?php echo $k ? $k : '' ?>" <?php if($k==$_ccExpYear): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <?php if($this->hasVerification()): ?>
    <li class="hide-if-token">
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_cid"><?php echo Mage::helper('payment')->__('Card Verification Number') ?> <span class="required">*</span></label><br/>
            <input type="text" title="<?php echo Mage::helper('payment')->__('Card Verification Number') ?>" class="required-entry input-text validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" style="width:3em;" value="<?php echo $this->getInfoData('cc_cid')?>"/>
        </div>
    </li>
    <?php endif; ?>
    <?php if($_model->useVault()): ?>
    <li class="hide-if-token" id="<?php echo $_code ?>_store_in_vault_div">
        <input type="checkbox" title="<?php echo $this->__('Save this card for future use') ?>" class="input-checkbox" id="<?php echo $_code ?>_save_card" name="payment[save_card]" value="1" <?php if($this->getInfoData('save_card')): ?>checked="checked"<?php endif ?> />
        <label for="<?php echo $_code ?>_save_card" style="float:none;"><?php echo $this->__('Save this card for future use') ?></label>
    </li>
    <?php endif; ?>
</ul>

<script type="text/javascript">
//<![CDATA[
(function() {
<?php if ($_useVault): ?>
    var enableDisableFields = function(disabled) {
        var code = "<?php echo $_code ?>";
        <?php if($this->hasVerification()): ?>
        var fields = ["_cc_type", "_cc_number", "_expiration", "_expiration_yr", "_cc_cid", "_save_card"];
        <?php else: ?>
        var fields = ["_cc_type", "_cc_number", "_expiration", "_expiration_yr", "_save_card"];
        <?php endif; ?>
        var id;
        for (id = 0; id < fields.length; id++) {
            $(code + fields[id]).disabled = disabled;
        }
    }
    
    var selectBox = $('<?php echo $_code ?>_token');
    var initToken = selectBox.getValue();
    
    if (initToken)
    {
        $$('.hide-if-token').invoke('hide');
        enableDisableFields("disabled");
    }
    $('<?php echo $_code ?>_token').observe('change', function (e) {
        var selectBox = $(this);
        var token = selectBox.getValue();
        if (token)
        {
        	$('<?php echo $_code ?>_cc_type').value = "";
            $('<?php echo $_code ?>_cc_number').value = "";
            $('<?php echo $_code ?>_expiration').value = "";
            $('<?php echo $_code ?>_expiration_yr').value = "";
            <?php if($this->hasVerification()): ?>
                $('<?php echo $_code ?>_cc_cid').value = "";
            <?php endif; ?>
            $('<?php echo $_code ?>_save_card').checked = false;
            $$('.hide-if-token').invoke('hide');
            enableDisableFields("disabled");
        }
        else
        {
            $('<?php echo $_code ?>_cc_type').value = "";
            $('<?php echo $_code ?>_cc_number').value = "";
            $('<?php echo $_code ?>_expiration').value = "";
            $('<?php echo $_code ?>_expiration_yr').value = "";
            <?php if($this->hasVerification()): ?>
                $('<?php echo $_code ?>_cc_cid').value = "";
            <?php endif; ?>
            $('<?php echo $_code ?>_save_card').checked = false;
            $$('.hide-if-token').invoke('show');
            enableDisableFields(false);
        }
    });
<?php endif; ?>
})();
//]]></script>