<?php
/**
 * Cardpay Solutions, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * PHP version 5
 * 
 * @category  Cardpay
 * @package   Cardpay_PayeezyLevel3
 * @copyright Copyright (c) 2015 Cardpay Solutions, Inc. (http://www.cardpaysolutions.com)
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<?php
$_code = $this->getMethodCode();
$_model = Mage::getModel('payeezylevel3/creditcard');
$_loggedIn = Mage::getSingleton('customer/session')->isLoggedIn();
$_savedCards = $_model->currentCustomerCards();
$_useVault = $_loggedIn && $_model->useVault() && count($_savedCards);
?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <?php if ($_useVault): ?>
    <li id="<?php echo $_code ?>_token_selector">
        <label for="<?php echo $_code ?>_cc_token"><?php echo $this->__('Payment Information') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_token" name="payment[token]">
                <?php foreach ($_savedCards as $card): ?>
                    <option value="<?php echo $card->getId() ?>" <?php echo $card->getIsDefault() ? 'selected="selected"' : '' ?>>
                        <?php echo $card->getMaskedCardNum() . ' - ' . $card->getCardTypeName(); ?>
                    </option>
                <?php endforeach; ?>
                    <option value=''><?php echo $this->__('Add new card') ?></option>
            </select>
        </div>
    </li>
    <?php endif; ?>
	<li class="hide-if-token">
        <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
                <option value=""><?php echo $this->__('--Please Select--')?></option>
            <?php $_ccType = $this->getInfoData('cc_type') ?>
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <li class="hide-if-token">
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" />
        </div>
    </li>
    <li class="hide-if-token" id="<?php echo $_code ?>_cc_type_exp_div">
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
    <?php if($this->hasVerification()): ?>
    <li class="hide-if-token" id="<?php echo $_code ?>_cc_type_cvv_div">
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
            </div>
            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
        </div>
    </li>
    <?php endif; ?>
    <?php if($this->canSaveCard()): ?>
    <li class="hide-if-token" id="<?php echo $_code ?>_store_in_vault_div">
        <input type="checkbox" title="<?php echo $this->__('Save this card for future use') ?>" class="input-checkbox" id="<?php echo $_code ?>_save_card" name="payment[save_card]" value="1" />
        <label for="<?php echo $_code ?>_save_card" class="required" style="float:none;"><?php echo $this->__('Save this card for future use') ?></label>
    </li>
    <?php endif; ?>
</ul>

<script type="text/javascript">
//<![CDATA[
(function() {
<?php if ($_useVault): ?>
    var selectBox = $('<?php echo $_code ?>_token');
    var initToken = selectBox.getValue();
    var cardsJson = [
    <?php foreach ($_savedCards as $card): ?>
        <?php echo Mage::helper('core')->jsonEncode($card->getData()) ?>,
    <?php endforeach; ?>
    ];
    
    if (initToken)
    {
        var initialCard = objectFindByKey(cardsJson, 'payeezylevel3_id', initToken);
        $('<?php echo $_code ?>_cc_type').value = initialCard.cc_type;
        $('<?php echo $_code ?>_cc_number').value = initialCard.token;
        $('<?php echo $_code ?>_expiration').value = initialCard.cc_exp_month;
        $('<?php echo $_code ?>_expiration_yr').value = initialCard.cc_exp_year;
        <?php if($this->hasVerification()): ?>
            $('<?php echo $_code ?>_cc_cid').value = "";
        <?php endif; ?>
        $('<?php echo $_code ?>_save_card').checked = false;
        $$('.hide-if-token').invoke('hide');
    }
    $('<?php echo $_code ?>_token').observe('change', function (e) {
        var selectBox = $(this);
        var token = selectBox.getValue();
        if (token)
        {
            var selectedCard = objectFindByKey(cardsJson, 'payeezylevel3_id', token);
            $('<?php echo $_code ?>_cc_type').value = selectedCard.cc_type;
            $('<?php echo $_code ?>_cc_number').value = selectedCard.token;
            $('<?php echo $_code ?>_expiration').value = selectedCard.cc_exp_month;
            $('<?php echo $_code ?>_expiration_yr').value = selectedCard.cc_exp_year;
            <?php if($this->hasVerification()): ?>
                $('<?php echo $_code ?>_cc_cid').value = "";
            <?php endif; ?>
            $('<?php echo $_code ?>_save_card').checked = false;
            $$('.hide-if-token').invoke('hide');
        }
        else
        {
            $('<?php echo $_code ?>_cc_type').value = "";
            $('<?php echo $_code ?>_cc_number').value = "";
            $('<?php echo $_code ?>_expiration').value = "";
            $('<?php echo $_code ?>_expiration_yr').value = "";
            <?php if($this->hasVerification()): ?>
                $('<?php echo $_code ?>_cc_cid').value = "";
            <?php endif; ?>
            $('<?php echo $_code ?>_save_card').checked = false;
            $$('.hide-if-token').invoke('show');
        }
    });
    
    function objectFindByKey(array, key, value) {
        for (var i = 0; i < array.length; i++) {
            if (array[i][key] === value) {
                return array[i];
            }
        }
        return null;
    }

<?php endif; ?>
})();
//]]></script>